const series = [
    { id: 'klassiker', name: 'Die drei ??? - Klassiker', color: '#1a5490' },
    { id: 'neuzeit', name: 'Die drei ??? - Neuzeit', color: '#2a7fb8' },
    { id: 'sonderausgaben', name: 'Die drei ??? - Sonderausgaben', color: '#e63946' },
    { id: 'sammelband', name: 'Die drei ??? - Sammelbände', color: '#06a77d' },
    { id: 'sonderband', name: 'Die drei ??? - Sonderbände', color: '#f77f00' },

    { id: 'kids', name: 'Die drei ??? Kids', color: '#8338ec' },
    { id: 'kids_rate', name: 'Die drei ??? Kids - Ratekrimis', color: '#9d4edd' },
    { id: 'kids_und_du', name: 'Die drei ??? Kids - und du', color: '#c77dff' },
    { id: 'kids_sammel', name: 'Die drei ??? Kids - Sammelbände', color: '#b5179e' },
    { id: 'kids_sonder', name: 'Die drei ??? Kids - Sonderbände', color: '#7209b7' },
    { id: 'kids_mini', name: 'Die drei ??? Kids - Minibände', color: '#560bad' },
];

const books = [
    // Die drei ??? - Klassiker
    { id: 'buch_01', name: 'und das Gespensterschloß', series: 'klassiker' },
    { id: 'buch_02', name: 'und der Super-Papagei', series: 'klassiker' },
    { id: 'buch_03', name: 'und die flüsternde Mumie', series: 'klassiker' },
    { id: 'buch_04', name: 'und der grüne Geist', series: 'klassiker' },
    { id: 'buch_05', name: 'und der verschwundene Schatz', series: 'klassiker' },
    { id: 'buch_06', name: 'und die Geisterinsel', series: 'klassiker' },
    { id: 'buch_07', name: 'und der Fluch des Rubins', series: 'klassiker' },
    { id: 'buch_08', name: 'und die silberne Spinne', series: 'klassiker' },
    { id: 'buch_09', name: 'und der seltsame Wecker', series: 'klassiker' },
    { id: 'buch_10', name: 'und der Teufelsberg', series: 'klassiker' },
    { id: 'buch_11', name: 'und der sprechende Totenkopf', series: 'klassiker' },
    { id: 'buch_12', name: 'und der lachende Schatten', series: 'klassiker' },
    { id: 'buch_13', name: 'und die schwarze Katze', series: 'klassiker' },
    { id: 'buch_14', name: 'und der unheimliche Drache', series: 'klassiker' },
    { id: 'buch_15', name: 'und die flammende Spur', series: 'klassiker' },
    { id: 'buch_16', name: 'und der rasende Löwe', series: 'klassiker' },
    { id: 'buch_17', name: 'und die singende Schlange', series: 'klassiker' },
    { id: 'buch_18', name: 'und die rätselhaften Bilder', series: 'klassiker' },
    { id: 'buch_19', name: 'und der Phantomsee', series: 'klassiker' },
    { id: 'buch_20', name: 'und das Bergmonster', series: 'klassiker' },
    { id: 'buch_21', name: 'und der Zauberspiegel', series: 'klassiker' },
    { id: 'buch_22', name: 'und die gefährliche Erbschaft', series: 'klassiker' },
    { id: 'buch_23', name: 'und der Karpatenhund', series: 'klassiker' },
    { id: 'buch_24', name: 'und die Silbermine', series: 'klassiker' },
    { id: 'buch_25', name: 'und der tanzende Teufel', series: 'klassiker' },
    { id: 'buch_26', name: 'und das Aztekenschwert', series: 'klassiker' },
    { id: 'buch_27', name: 'und der magische Kreis', series: 'klassiker' },
    { id: 'buch_28', name: 'und der Doppelgänger', series: 'klassiker' },
    { id: 'buch_29', name: 'und der Ameisenmensch', series: 'klassiker' },
    { id: 'buch_30', name: 'und das Riff der Haie', series: 'klassiker' },
    { id: 'buch_31', name: 'und das Narbengesicht', series: 'klassiker' },
    { id: 'buch_32', name: 'und die bedrohte Ranch', series: 'klassiker' },
    { id: 'buch_33', name: 'und der rote Pirat', series: 'klassiker' },
    { id: 'buch_34', name: 'und der Höhlenmensch', series: 'klassiker' },
    { id: 'buch_35', name: 'und der Super-Wal', series: 'klassiker' },
    { id: 'buch_36', name: 'und der heimliche Hehler', series: 'klassiker' },
    { id: 'buch_37', name: 'und der unsichtbare Gegner', series: 'klassiker' },
    { id: 'buch_38', name: 'und die Perlenvögel', series: 'klassiker' },
    { id: 'buch_39', name: 'und der Automarder', series: 'klassiker' },
    { id: 'buch_40', name: 'und das Volk der Winde', series: 'klassiker' },
    { id: 'buch_41', name: 'und der weinende Sarg', series: 'klassiker' },
    { id: 'buch_42', name: 'und der höllische Werwolf', series: 'klassiker' },
    { id: 'buch_43', name: 'und der gestohlene Preis', series: 'klassiker' },
    { id: 'buch_44', name: 'und das Gold der Wikinger', series: 'klassiker' },
    { id: 'buch_45', name: 'und der schrullige Millionär', series: 'klassiker' },
    { id: 'buch_46', name: 'und die Comic-Diebe', series: 'klassiker' },
    { id: 'buch_47', name: 'und die gefährlichen Fässer', series: 'klassiker' },
    { id: 'buch_48', name: 'und der giftige Gockel', series: 'klassiker' },
    { id: 'buch_49', name: 'und die Automafia', series: 'klassiker' },
    { id: 'buch_50', name: 'und die Musikpiraten', series: 'klassiker' },
    { id: 'buch_51', name: 'und der verschwundene Filmstar', series: 'klassiker' },
    { id: 'buch_52', name: 'und der riskante Ritt', series: 'klassiker' },
    { id: 'buch_53', name: 'Gekaufte Spieler', series: 'klassiker' },
    { id: 'buch_54', name: 'Gefahr im Verzug', series: 'klassiker' },
    { id: 'buch_55', name: 'Angriff der Computer-Viren', series: 'klassiker' },

    // Die drei ??? - Neuzeit
    { id: 'buch_56', name: 'Tatort Zirkus', series: 'neuzeit' },
    { id: 'buch_57', name: 'und der verrückte Maler', series: 'neuzeit' },
    { id: 'buch_58', name: 'Giftiges Wasser', series: 'neuzeit' },
    { id: 'buch_59', name: 'Dopingmixer', series: 'neuzeit' },
    { id: 'buch_60', name: 'und die Rache des Tigers', series: 'neuzeit' },
    { id: 'buch_61', name: 'Spuk im Hotel', series: 'neuzeit' },
    { id: 'buch_62', name: 'Fußball-Gangster', series: 'neuzeit' },
    { id: 'buch_63', name: 'Geisterstadt', series: 'neuzeit' },
    { id: 'buch_64', name: 'Diamantenschmuggel', series: 'neuzeit' },
    { id: 'buch_65', name: 'und die Schattenmänner', series: 'neuzeit' },
    { id: 'buch_66', name: 'Geheimnis der Särge', series: 'neuzeit' },
    { id: 'buch_67', name: 'Schatz im Bergsee', series: 'neuzeit' },
    { id: 'buch_68', name: 'Späte Rache', series: 'neuzeit' },
    { id: 'buch_69', name: 'Schüsse aus dem Dunkel', series: 'neuzeit' },
    { id: 'buch_70', name: 'Die verschwundene Seglerin', series: 'neuzeit' },
    { id: 'buch_71', name: 'Dreckiger Deal', series: 'neuzeit' },
    { id: 'buch_72', name: 'Poltergeist', series: 'neuzeit' },
    { id: 'buch_73', name: 'und das brennende Schwert', series: 'neuzeit' },
    { id: 'buch_74', name: 'Die Spur des Raben', series: 'neuzeit' },
    { id: 'buch_75', name: 'Stimmen aus dem Nichts', series: 'neuzeit' },
    { id: 'buch_76', name: 'Pistenteufel', series: 'neuzeit' },
    { id: 'buch_77', name: 'Das leere Grab', series: 'neuzeit' },
    { id: 'buch_78', name: 'Im Bann des Voodoo', series: 'neuzeit' },
    { id: 'buch_79', name: 'Geheimsache Ufo', series: 'neuzeit' },
    { id: 'buch_80', name: 'Verdeckte Fouls', series: 'neuzeit' },
    { id: 'buch_81', name: 'Die Karten des Bösen', series: 'neuzeit' },
    { id: 'buch_82', name: 'Meuterei auf hoher See', series: 'neuzeit' },
    { id: 'buch_83', name: 'Musik des Teufels', series: 'neuzeit' },
    { id: 'buch_84', name: 'Feuerturm', series: 'neuzeit' },
    { id: 'buch_85', name: 'Nacht in Angst', series: 'neuzeit' },
    { id: 'buch_86', name: 'Wolfsgesicht', series: 'neuzeit' },
    { id: 'buch_87', name: 'Vampir im Internet', series: 'neuzeit' },
    { id: 'buch_88', name: 'Tödliche Spur', series: 'neuzeit' },
    { id: 'buch_89', name: 'Der Feuerteufel', series: 'neuzeit' },
    { id: 'buch_90', name: 'Labyrinth der Götter', series: 'neuzeit' },
    { id: 'buch_91', name: 'Todesflug', series: 'neuzeit' },
    { id: 'buch_92', name: 'und das Geisterschiff', series: 'neuzeit' },
    { id: 'buch_93', name: 'Das schwarze Monster', series: 'neuzeit' },
    { id: 'buch_94', name: 'Botschaft von Geisterhand', series: 'neuzeit' },
    { id: 'buch_95', name: 'und der rote Rächer', series: 'neuzeit' },
    { id: 'buch_96', name: 'Insektenstachel', series: 'neuzeit' },
    { id: 'buch_97', name: 'Tal des Schreckens', series: 'neuzeit' },
    { id: 'buch_98', name: 'Rufmord', series: 'neuzeit' },
    { id: 'buch_99', name: 'Toteninsel', series: 'neuzeit' },
    { id: 'buch_100', name: 'und das Hexenhandy', series: 'neuzeit' },
    { id: 'buch_101', name: 'Doppelte Täuschung', series: 'neuzeit' },
    { id: 'buch_102', name: 'Das Erbe des Meisterdiebs', series: 'neuzeit' },
    { id: 'buch_103', name: 'Gift per E-Mail', series: 'neuzeit' },
    { id: 'buch_104', name: 'und der Nebelberg', series: 'neuzeit' },
    { id: 'buch_105', name: 'Der Mann ohne Kopf', series: 'neuzeit' },
    { id: 'buch_106', name: 'und der Schatz der Mönche', series: 'neuzeit' },
    { id: 'buch_107', name: 'Die sieben Tore', series: 'neuzeit' },
    { id: 'buch_108', name: 'Gefährliches Quiz', series: 'neuzeit' },
    { id: 'buch_109', name: 'Panik im Park', series: 'neuzeit' },
    { id: 'buch_110', name: 'Die Höhle des Grauens', series: 'neuzeit' },
    { id: 'buch_111', name: 'Schlucht der Dämonen', series: 'neuzeit' },
    { id: 'buch_112', name: 'Das Auge des Drachen', series: 'neuzeit' },
    { id: 'buch_113', name: 'Die Villa der Toten', series: 'neuzeit' },
    { id: 'buch_114', name: 'Auf tödlichem Kurs', series: 'neuzeit' },
    { id: 'buch_115', name: 'Codename: Cobra', series: 'neuzeit' },
    { id: 'buch_116', name: 'Der finstere Rivale', series: 'neuzeit' },
    { id: 'buch_117', name: 'Das düstere Vermächtnis', series: 'neuzeit' },
    { id: 'buch_118', name: 'Der geheime Schlüssel', series: 'neuzeit' },
    { id: 'buch_119', name: 'Der schwarze Skorpion', series: 'neuzeit' },
    { id: 'buch_120', name: 'Spur ins Nichts', series: 'neuzeit' },
    { id: 'buch_121', name: 'und der Geisterzug', series: 'neuzeit' },
    { id: 'buch_122', name: 'Fußballfieber', series: 'neuzeit' },
    { id: 'buch_123', name: 'Geister-Canyon', series: 'neuzeit' },
    { id: 'buch_124', name: 'Feuermond', series: 'neuzeit' },
    { id: 'buch_125', name: 'Schrecken aus dem Moor', series: 'neuzeit' },
    { id: 'buch_126', name: 'Schwarze Madonna', series: 'neuzeit' },
    { id: 'buch_127', name: 'Schatten über Hollywood', series: 'neuzeit' },
    { id: 'buch_128', name: 'SMS aus dem Grab', series: 'neuzeit' },
    { id: 'buch_129', name: 'Der Fluch des Drachen', series: 'neuzeit' },
    { id: 'buch_130', name: 'Haus des Schreckens', series: 'neuzeit' },
    { id: 'buch_131', name: 'Spuk im Netz', series: 'neuzeit' },
    { id: 'buch_132', name: 'Fels der Dämonen', series: 'neuzeit' },
    { id: 'buch_133', name: 'Der tote Mönch', series: 'neuzeit' },
    { id: 'buch_134', name: 'Fluch des Piraten', series: 'neuzeit' },
    { id: 'buch_135', name: 'und das versunkene Dorf', series: 'neuzeit' },
    { id: 'buch_136', name: 'Pfad der Angst', series: 'neuzeit' },
    { id: 'buch_137', name: 'Die geheime Treppe', series: 'neuzeit' },
    { id: 'buch_138', name: 'Das Geheimnis der Diva', series: 'neuzeit' },
    { id: 'buch_139', name: 'Stadt der Vampire', series: 'neuzeit' },
    { id: 'buch_140', name: 'und die Fußball-Falle', series: 'neuzeit' },
    { id: 'buch_141', name: 'Tödliches Eis', series: 'neuzeit' },
    { id: 'buch_142', name: 'und die Poker-Hölle', series: 'neuzeit' },
    { id: 'buch_143', name: 'Zwillinge der Finsternis', series: 'neuzeit' },
    { id: 'buch_144', name: 'und die Rache der Samurai', series: 'neuzeit' },
    { id: 'buch_145', name: 'Der Biss der Bestie', series: 'neuzeit' },
    { id: 'buch_146', name: 'Grusel auf Campbell Castle', series: 'neuzeit' },
    { id: 'buch_147', name: 'und die feurige Flut', series: 'neuzeit' },
    { id: 'buch_148', name: 'Der namenlose Gegner', series: 'neuzeit' },
    { id: 'buch_149', name: 'Geisterbucht', series: 'neuzeit' },
    { id: 'buch_150', name: 'Schwarze Sonne', series: 'neuzeit' },
    { id: 'buch_151', name: 'Skateboardfieber', series: 'neuzeit' },
    { id: 'buch_152', name: 'und das Fußballphantom', series: 'neuzeit' },
    { id: 'buch_153', name: 'Botschaft aus der Unterwelt', series: 'neuzeit' },
    { id: 'buch_154', name: 'und der Meister des Todes', series: 'neuzeit' },
    { id: 'buch_155', name: 'Im Netz des Drachen', series: 'neuzeit' },
    { id: 'buch_156', name: 'Im Zeichen der Schlangen', series: 'neuzeit' },
    { id: 'buch_157', name: 'und der Feuergeist', series: 'neuzeit' },
    { id: 'buch_158', name: 'Nacht der Tiger', series: 'neuzeit' },
    { id: 'buch_159', name: 'Geheimnisvolle Botschaften', series: 'neuzeit' },
    { id: 'buch_160', name: 'Die blutenden Bilder', series: 'neuzeit' },
    { id: 'buch_161', name: 'und der schreiende Nebel', series: 'neuzeit' },
    { id: 'buch_162', name: 'und der verschollene Pilot', series: 'neuzeit' },
    { id: 'buch_163', name: 'Fußball-Teufel', series: 'neuzeit' },
    { id: 'buch_164', name: 'Im Schatten des Giganten', series: 'neuzeit' },
    { id: 'buch_165', name: 'und die brennende Stadt', series: 'neuzeit' },
    { id: 'buch_166', name: 'und das blaue Biest', series: 'neuzeit' },
    { id: 'buch_167', name: 'GPS-Gangster', series: 'neuzeit' },
    { id: 'buch_168', name: 'Die Spur des Spielers', series: 'neuzeit' },
    { id: 'buch_169', name: 'Straße des Grauens', series: 'neuzeit' },
    { id: 'buch_170', name: 'und das Phantom aus dem Meer', series: 'neuzeit' },
    { id: 'buch_171', name: 'und der Eisenmann', series: 'neuzeit' },
    { id: 'buch_172', name: 'Dämon der Rache', series: 'neuzeit' },
    { id: 'buch_173', name: 'und das Tuch der Toten', series: 'neuzeit' },
    { id: 'buch_174', name: 'Schattenwelt', series: 'neuzeit' },
    { id: 'buch_175', name: 'und der gestohlene Sieg', series: 'neuzeit' },
    { id: 'buch_176', name: 'Sinfonie der Angst', series: 'neuzeit' },
    { id: 'buch_177', name: 'Der Geist des Goldgräbers', series: 'neuzeit' },
    { id: 'buch_178', name: 'Der gefiederte Schrecken', series: 'neuzeit' },
    { id: 'buch_179', name: 'Die Rache des Untoten', series: 'neuzeit' },
    { id: 'buch_180', name: 'und die flüsternden Puppen', series: 'neuzeit' },
    { id: 'buch_181', name: 'Das Kabinett des Zauberers', series: 'neuzeit' },
    { id: 'buch_182', name: 'Im Haus des Henkers', series: 'neuzeit' },
    { id: 'buch_183', name: 'und der letzte Song', series: 'neuzeit' },
    { id: 'buch_184', name: 'und der Hexengarten', series: 'neuzeit' },
    { id: 'buch_185', name: 'und der Mann ohne Augen', series: 'neuzeit' },
    { id: 'buch_186', name: 'Insel des Vergessens', series: 'neuzeit' },
    { id: 'buch_187', name: 'und das silberne Amulett', series: 'neuzeit' },
    { id: 'buch_188', name: 'Signale aus dem Jenseits', series: 'neuzeit' },
    { id: 'buch_189', name: 'und der unsichtbare Passagier', series: 'neuzeit' },
    { id: 'buch_190', name: 'und die Kammer der Rätsel', series: 'neuzeit' },
    { id: 'buch_191', name: 'Verbrechen im Nichts', series: 'neuzeit' },
    { id: 'buch_192', name: 'Im Bann des Drachen', series: 'neuzeit' },
    { id: 'buch_193', name: 'Schrecken aus der Tiefe', series: 'neuzeit' },
    { id: 'buch_194', name: 'und die Zeitreisende', series: 'neuzeit' },
    { id: 'buch_195', name: 'Im Reich der Ungeheuer', series: 'neuzeit' },
    { id: 'buch_196', name: 'Geheimnis des Bauchredners', series: 'neuzeit' },
    { id: 'buch_197', name: 'Im Auge des Sturms', series: 'neuzeit' },
    { id: 'buch_198', name: 'Die Legende der Gaukler', series: 'neuzeit' },
    { id: 'buch_199', name: 'und der grüne Kobold', series: 'neuzeit' },
    { id: 'buch_200', name: 'Feuriges Auge', series: 'neuzeit' },
    { id: 'buch_201', name: 'Höhenangst', series: 'neuzeit' },
    { id: 'buch_202', name: 'Das weiße Grab', series: 'neuzeit' },
    { id: 'buch_203', name: 'Tauchgang ins Ungewisse', series: 'neuzeit' },
    { id: 'buch_204', name: 'Der dunkle Wächter', series: 'neuzeit' },
    { id: 'buch_205', name: 'Das rätselhafte Erbe', series: 'neuzeit' },
    { id: 'buch_206', name: 'und der Mottenmann', series: 'neuzeit' },
    { id: 'buch_207', name: 'Die falschen Detektive', series: 'neuzeit' },
    { id: 'buch_208', name: 'und der dunkle Taipan', series: 'neuzeit' },
    { id: 'buch_209', name: 'Kelch des Schicksals', series: 'neuzeit' },
    { id: 'buch_210', name: 'Kreaturen der Nacht', series: 'neuzeit' },
    { id: 'buch_211', name: 'und die schweigende Grotte', series: 'neuzeit' },
    { id: 'buch_212', name: 'und der Jadekönig', series: 'neuzeit' },
    { id: 'buch_213', name: 'und der weiße Leopard', series: 'neuzeit' },
    { id: 'buch_214', name: 'Der Fluch der Medusa', series: 'neuzeit' },
    { id: 'buch_215', name: 'und der Geisterbunker', series: 'neuzeit' },
    { id: 'buch_216', name: 'und die verlorene Zeit', series: 'neuzeit' },
    { id: 'buch_217', name: 'Die Schwingen des Unheils', series: 'neuzeit' },
    { id: 'buch_218', name: 'und der Kristallschädel', series: 'neuzeit' },
    { id: 'buch_219', name: 'Im Netz der Lügen', series: 'neuzeit' },
    { id: 'buch_220', name: 'und die Teufelsklippe', series: 'neuzeit' },
    { id: 'buch_221', name: 'Im Wald der Gefahren', series: 'neuzeit' },
    { id: 'buch_222', name: 'Manuskript des Satans', series: 'neuzeit' },
    { id: 'buch_223', name: 'und die Gesetzlosen', series: 'neuzeit' },
    { id: 'buch_224', name: 'und der Knochenmann', series: 'neuzeit' },
    { id: 'buch_225', name: 'Die Yacht des Verrats', series: 'neuzeit' },
    { id: 'buch_226', name: 'und der Puppenmacher', series: 'neuzeit' },
    { id: 'buch_227', name: 'Die Spur der Toten', series: 'neuzeit' },
    { id: 'buch_228', name: 'Melodie der Rache', series: 'neuzeit' },
    { id: 'buch_229', name: 'Der Ruf der Krähen', series: 'neuzeit' },
    { id: 'buch_230', name: 'Drehbuch der Täuschung', series: 'neuzeit' },
    { id: 'buch_231', name: 'Der Tag der Toten', series: 'neuzeit' },
    { id: 'buch_232', name: 'und der Dreiäugige Schakal', series: 'neuzeit' },
    { id: 'buch_233', name: 'Die Stadt aus Gold', series: 'neuzeit' },
    { id: 'buch_234', name: 'Die Nacht der Gewitter', series: 'neuzeit' },
    { id: 'buch_235', name: 'und der lebende Tresor', series: 'neuzeit' },
    { id: 'buch_236', name: 'und das Fantasmofon', series: 'neuzeit' },
    { id: 'buch_237', name: 'Im Bann des Barrakudas', series: 'neuzeit' },
    { id: 'buch_238', name: 'und der rote Büffel', series: 'neuzeit' },
    { id: 'buch_239', name: 'Falsche Schuld', series: 'neuzeit' },
    { id: 'buch_240', name: 'Das Geheimnis der sieben Palmen', series: 'neuzeit' },
    { id: 'buch_241', name: 'und die schwarze Rose', series: 'neuzeit' },
    { id: 'buch_242', name: 'Meister des Lichts', series: 'neuzeit' },
    { id: 'buch_243', name: 'und das weiße Auge', series: 'neuzeit' },
    { id: 'buch_244', name: 'Fußball-Skandal', series: 'neuzeit' },
    { id: 'buch_245', name: 'Das Lied der Knochenflöte', series: 'neuzeit' },
    { id: 'buch_246', name: 'Rätsel des Mondes', series: 'neuzeit' },
    { id: 'buch_247', name: 'Spuk in Hollywood', series: 'neuzeit' },
    { id: 'buch_248', name: 'im Griff der Sandgeister', series: 'neuzeit' },
    { id: 'buch_249', name: 'Unter Verdacht', series: 'neuzeit' },

    // Die drei ??? - Sonderausgaben
    { id: 'buch_400', name: 'und die Geisterlampe', series: 'sonderausgaben' },
    { id: 'buch_401', name: 'Top Secret Edition', series: 'sonderausgaben' },
    { id: 'buch_402', name: 'und der dreiTag', series: 'sonderausgaben' },
    { id: 'buch_403', name: 'Das Rätsel der Sieben', series: 'sonderausgaben' },
    { id: 'buch_404', name: 'Dein Fall - Tödlicher Dreh', series: 'sonderausgaben' },
    { id: 'buch_405', name: 'und der 5. Advent', series: 'sonderausgaben' },
    { id: 'buch_406', name: 'und das kalte Auge', series: 'sonderausgaben' },
    { id: 'buch_407', name: 'Das Grab der Inka-Mumie', series: 'sonderausgaben' },
    { id: 'buch_408', name: 'und der Tornadojäger', series: 'sonderausgaben' },
    { id: 'buch_409', name: 'Dein Fall - Hotel der Diebe', series: 'sonderausgaben' },
    { id: 'buch_410', name: 'und der Zeitgeist', series: 'sonderausgaben' },
    { id: 'buch_411', name: 'Top Secret Edition 2', series: 'sonderausgaben' },
    { id: 'buch_412', name: 'Dein Fall - Die weiße Anakonda', series: 'sonderausgaben' },
    { id: 'buch_413', name: 'Dein Fall - Höllenfahrt', series: 'sonderausgaben' },
    { id: 'buch_414', name: 'und der dreiäugige Totenkopf - Graphic Novel', series: 'sonderausgaben' },
    { id: 'buch_415', name: 'Stille Nacht, düstere Nacht', series: 'sonderausgaben' },
    { id: 'buch_416', name: 'und das Grab der Maya ', series: 'sonderausgaben' },
    { id: 'buch_417', name: 'Dein Fall - Das Rätsel der Smart City', series: 'sonderausgaben' },
    { id: 'buch_418', name: 'und der schwarze Tag', series: 'sonderausgaben' },
    { id: 'buch_419', name: 'Das Dorf der Teufel - Graphic Novel', series: 'sonderausgaben' },
    { id: 'buch_420', name: 'Bobs Archiv - Der Fall Marty Fielding', series: 'sonderausgaben' },
    { id: 'buch_421', name: 'Dein Fall - Wüstenfieber', series: 'sonderausgaben' },
    { id: 'buch_422', name: 'und die Totenkopfbucht', series: 'sonderausgaben' },
    { id: 'buch_423', name: 'Das Ritual der Schlangen - Graphic Novel', series: 'sonderausgaben' },
    { id: 'buch_424', name: 'O du finstere', series: 'sonderausgaben' },
    { id: 'buch_425', name: 'Dein Fall - Teuflisches Foul', series: 'sonderausgaben' },
    { id: 'buch_426', name: 'Der verrückte Professor', series: 'sonderausgaben' },
    { id: 'buch_427', name: 'Rocky Beach - Graphic Novel', series: 'sonderausgaben' },
    { id: 'buch_428', name: 'und die Geisterfrau', series: 'sonderausgaben' },
    { id: 'buch_429', name: 'Eine schreckliche Bescherung', series: 'sonderausgaben' },
    { id: 'buch_430', name: 'und der Höllenzug', series: 'sonderausgaben' },
    { id: 'buch_431', name: 'Der Goldene Salamander - Graphic Novel', series: 'sonderausgaben' },
    { id: 'buch_432', name: 'Dein Fall - und die Gefängnisinsel', series: 'sonderausgaben' },
    { id: 'buch_433', name: 'und das Gespensterschloss - Graphic Novel', series: 'sonderausgaben' },
    { id: 'buch_434', name: 'und das Phantom-Krokodil', series: 'sonderausgaben' },
    { id: 'buch_435', name: 'und die flüsternde Mumie - Graphic Novel', series: 'sonderausgaben' },
    { id: 'buch_436', name: 'und die Salztote', series: 'sonderausgaben' },
    { id: 'buch_437', name: 'Rocky Beach Crimes - Tödliche Törtchen', series: 'sonderausgaben' },
    { id: 'buch_438', name: 'Rocky Beach Crimes - Mord unter Palmen', series: 'sonderausgaben' },
    { id: 'buch_439', name: 'und die rätselhaften Bilder - Graphic Novel', series: 'sonderausgaben' },
    { id: 'buch_440', name: 'Rocky Beach Crimes - Eiskalter Rausch', series: 'sonderausgaben' },
    { id: 'buch_441', name: 'Hotel Bigfoot - Graphic Novel', series: 'sonderausgaben' },
    { id: 'buch_442', name: 'Böser die Glocken nie klingen', series: 'sonderausgaben' },
    { id: 'buch_443', name: 'Dein Fall - und der schwarze Fluch', series: 'sonderausgaben' },
    { id: 'buch_444', name: 'Rocky Beach Crimes - Der blutrote Kondor', series: 'sonderausgaben' },
    { id: 'buch_445', name: 'und der schreiende Zug', series: 'sonderausgaben' },
    { id: 'buch_446', name: 'Gruselige Weihnacht überall', series: 'sonderausgaben' },
    { id: 'buch_447', name: 'und der Bärenkopf', series: 'sonderausgaben' },
    { id: 'buch_448', name: 'Rätsel des Flamingos', series: 'sonderausgaben' },
    { id: 'buch_449', name: 'und die rasende Gier', series: 'sonderausgaben' },
    { id: 'buch_450', name: 'und das Geheimnis von Black Mesa', series: 'sonderausgaben' },
    { id: 'buch_451', name: 'Rocky Beach Crimes - Gefährliche Gentlemen', series: 'sonderausgaben' },
    { id: 'buch_452', name: 'Justus Jonas - Graphic Novel', series: 'sonderausgaben' },
    { id: 'buch_453', name: 'Phantom Highway - Graphic Novel', series: 'sonderausgaben' },
    { id: 'buch_454', name: 'Die Auferstehung', series: 'sonderausgaben' },
    { id: 'buch_455', name: 'O Geisterbaum', series: 'sonderausgaben' },
    { id: 'buch_456', name: 'Nacht in der Tiefe', series: 'sonderausgaben' },
    { id: 'buch_457', name: 'Rocky Beach Crimes - Salto mortale', series: 'sonderausgaben' },
    { id: 'buch_458', name: 'Peter Shaw - Graphic Novel', series: 'sonderausgaben' },
    { id: 'buch_459', name: 'Leise rieselt das Grauen', series: 'sonderausgaben' },

    // Die drei ??? – Sammelbände
    { id: 'sammel_01', name: 'Hochspannung x 3', series: 'sammelbaende' },
    { id: 'sammel_02', name: 'Nichts für schwache Nerven', series: 'sammelbaende' },
    { id: 'sammel_03', name: 'Krimifieber', series: 'sammelbaende' },
    { id: 'sammel_04', name: 'Nervenkitzel', series: 'sammelbaende' },
    { id: 'sammel_05', name: 'Super Spannung', series: 'sammelbaende' },
    { id: 'sammel_06', name: 'Hochexplosiv', series: 'sammelbaende' },
    { id: 'sammel_07', name: 'Sabotage', series: 'sammelbaende' },
    { id: 'sammel_08', name: 'Geisterstunde', series: 'sammelbaende' },
    { id: 'sammel_09', name: 'Eiskalt', series: 'sammelbaende' },
    { id: 'sammel_10', name: 'Streng geheim', series: 'sammelbaende' },
    { id: 'sammel_11', name: 'Im Bann der Phantome', series: 'sammelbaende' },
    { id: 'sammel_12', name: 'Geisterwelten', series: 'sammelbaende' },
    { id: 'sammel_13', name: 'Dämonen der Nacht', series: 'sammelbaende' },
    { id: 'sammel_14', name: 'Das Grauen im Nacken', series: 'sammelbaende' },
    { id: 'sammel_15', name: 'Tödliches Spiel', series: 'sammelbaende' },
    { id: 'sammel_16', name: 'Gejagte Schatten', series: 'sammelbaende' },
    { id: 'sammel_17', name: 'Todesstille', series: 'sammelbaende' },
    { id: 'sammel_18', name: 'Gefangen im Netz', series: 'sammelbaende' },
    { id: 'sammel_19', name: 'Gefährliches Spiel', series: 'sammelbaende' },
    { id: 'sammel_20', name: 'Schrecken der Nacht', series: 'sammelbaende' },
    { id: 'sammel_21', name: 'Toteninsel (alle drei Teile in einem Band)', series: 'sammelbaende' },
    { id: 'sammel_22', name: 'Flammen des Bösen', series: 'sammelbaende' },
    { id: 'sammel_23', name: 'Fußball-Krimis', series: 'sammelbaende' },
    { id: 'sammel_24', name: 'Black Edition', series: 'sammelbaende' },
    { id: 'sammel_25', name: 'Stadt der Gespenster', series: 'sammelbaende' },
    { id: 'sammel_26', name: 'Black Edition II', series: 'sammelbaende' },
    { id: 'sammel_27', name: 'Tödliche Täuschung', series: 'sammelbaende' },
    { id: 'sammel_28', name: 'Black Edition III', series: 'sammelbaende' },
    { id: 'sammel_29', name: 'Feuermond (alle drei Teile in einem Band)', series: 'sammelbaende' },
    { id: 'sammel_30', name: '… und die Stunde des Grauens', series: 'sammelbaende' },
    { id: 'sammel_31', name: 'Todesgefahr', series: 'sammelbaende' },
    { id: 'sammel_32', name: 'Tatort Fußball', series: 'sammelbaende' },
    { id: 'sammel_33', name: 'Spur des Bösen', series: 'sammelbaende' },
    { id: 'sammel_34', name: 'Im Labyrinth des Schreckens', series: 'sammelbaende' },
    { id: 'sammel_35', name: 'Fußballfluch', series: 'sammelbaende' },
    { id: 'sammel_36', name: 'Brennende Gefahr', series: 'sammelbaende' },
    { id: 'sammel_37', name: 'Teuflische Gegner', series: 'sammelbaende' },
    { id: 'sammel_38', name: 'Grabesstimmen', series: 'sammelbaende' },
    { id: 'sammel_39', name: 'Drachen / Rivale / Geisterzug', series: 'sammelbaende' },
    { id: 'sammel_40', name: 'Fouls / Fußballfieber / Fußballphantom', series: 'sammelbaende' },
    { id: 'sammel_41', name: 'Zeit der Bestien', series: 'sammelbaende' },

    // Die drei ??? – Sonderbände
    { id: 'sonder_01', name: 'Die drei ??? und ihr Rätsel-Handbuch', series: 'sonderband' },
    { id: 'sonder_02', name: 'Die drei ??? verraten Tipps und Tricks', series: 'sonderband' },
    { id: 'sonder_03', name: 'Die drei ??? Detektivhandbuch', series: 'sonderband' },
    { id: 'sonder_04', name: 'Die drei ??? Trainingsbuch für Detektive', series: 'sonderband' },
    { id: 'sonder_05', name: 'Die drei ??? Handbuch Geheimbotschaften', series: 'sonderband' },
    { id: 'sonder_06', name: 'Die drei ??? Survival-Buch', series: 'sonderband' },
    { id: 'sonder_07', name: 'Die drei ??? Das große Detektivhandbuch', series: 'sonderband' },
    { id: 'sonder_08', name: 'Die drei ??? Das Alleswisserbuch für Detektive', series: 'sonderband' },
    { id: 'sonder_09', name: 'Die drei ??? Rätsel knacken mit Justus Jonas', series: 'sonderband' },
    { id: 'sonder_10', name: 'Die drei ??? Querdenken mit Justus Jonas', series: 'sonderband' },
    { id: 'sonder_11', name: 'Die drei ??? und die kniffligsten Rätsel', series: 'sonderband' },
    { id: 'sonder_12', name: 'Die drei ??? und das sprechende Labyrinth', series: 'sonderband' },
    { id: 'sonder_13', name: 'Die drei ??? und das unheimliche Labyrinth', series: 'sonderband' },
    { id: 'sonder_14', name: 'Die drei ??? Denksport mit Justus Jonas', series: 'sonderband' },
    { id: 'sonder_15', name: 'Die drei ??? und der grüne Geist – Kalkofe kommentiert', series: 'sonderband' },

    // Die drei ??? Kids
    { id: 'kids_01', name: 'Panik im Paradies', series: 'kids' },
    { id: 'kids_02', name: 'Radio Rocky Beach', series: 'kids' },
    { id: 'kids_03', name: 'Invasion der Fliegen', series: 'kids' },
    { id: 'kids_04', name: 'Chaos vor der Kamera', series: 'kids' },
    { id: 'kids_05', name: 'Flucht in die Zukunft', series: 'kids' },
    { id: 'kids_06', name: 'Gefahr im Gruselgarten', series: 'kids' },
    { id: 'kids_07', name: 'Gruft der Piraten', series: 'kids' },
    { id: 'kids_08', name: 'Nacht unter Wölfen', series: 'kids' },
    { id: 'kids_09', name: 'SOS über den Wolken', series: 'kids' },
    { id: 'kids_10', name: 'Spuk in Rocky Beach', series: 'kids' },
    { id: 'kids_11', name: 'Fluch des Goldes', series: 'kids' },
    { id: 'kids_12', name: 'Internetpiraten', series: 'kids' },
    { id: 'kids_13', name: 'Im Reich der Rätsel', series: 'kids' },
    { id: 'kids_14', name: 'Gefahr aus dem All', series: 'kids' },
    { id: 'kids_15', name: 'In der Geisterstadt', series: 'kids' },
    { id: 'kids_16', name: 'Der magische Brunnen', series: 'kids' },
    { id: 'kids_17', name: 'Rettet Atlantis!', series: 'kids' },
    { id: 'kids_18', name: 'Mission Maulwurf', series: 'kids' },
    { id: 'kids_19', name: 'Spur in die Wildnis', series: 'kids' },
    { id: 'kids_20', name: 'Die Schmugglerinsel', series: 'kids' },
    { id: 'kids_21', name: 'Die Geisterjäger', series: 'kids' },
    { id: 'kids_22', name: 'Einarmige Banditen', series: 'kids' },
    { id: 'kids_23', name: 'Feuer in Rocky Beach', series: 'kids' },
    { id: 'kids_24', name: 'Im Banne des Zauberers', series: 'kids' },
    { id: 'kids_25', name: 'In letzter Sekunde', series: 'kids' },
    { id: 'kids_26', name: 'Fußball-Alarm', series: 'kids' },
    { id: 'kids_27', name: 'Die Schokofalle', series: 'kids' },
    { id: 'kids_28', name: 'Diamantenjagd', series: 'kids' },
    { id: 'kids_29', name: 'Monsterpilze', series: 'kids' },
    { id: 'kids_30', name: 'Im Geisterschiff', series: 'kids' },
    { id: 'kids_31', name: 'Rückkehr der Saurier', series: 'kids' },
    { id: 'kids_32', name: 'Die Gruselfalle', series: 'kids' },
    { id: 'kids_33', name: 'Nacht im Kerker', series: 'kids' },
    { id: 'kids_34', name: 'Falsches Gold', series: 'kids' },
    { id: 'kids_35', name: 'Im Wilden Westen', series: 'kids' },
    { id: 'kids_36', name: 'Mission Mars', series: 'kids' },
    { id: 'kids_37', name: 'Der Fluch der Indianer', series: 'kids' },
    { id: 'kids_38', name: 'Stunde der Wahrheit', series: 'kids' },
    { id: 'kids_39', name: 'Der verrückte Professor', series: 'kids' },
    { id: 'kids_40', name: 'Brennendes Eis', series: 'kids' },
    { id: 'kids_41', name: 'Insel der Haie', series: 'kids' },
    { id: 'kids_42', name: 'Fußballgötter', series: 'kids' },
    { id: 'kids_43', name: 'Duell der Ritter', series: 'kids' },
    { id: 'kids_44', name: 'Monster in Rocky Beach', series: 'kids' },
    { id: 'kids_45', name: 'Ein Fall für Superhelden', series: 'kids' },
    { id: 'kids_46', name: 'Jagd auf das Dino-Ei', series: 'kids' },
    { id: 'kids_47', name: 'Falsche Fußball-Freunde', series: 'kids' },
    { id: 'kids_48', name: 'Tanz der Skelette', series: 'kids' },
    { id: 'kids_49', name: 'Der Singende Geist', series: 'kids' },
    { id: 'kids_50', name: 'Schatz der Piraten', series: 'kids' },
    { id: 'kids_51', name: 'Tatort Kletterpark', series: 'kids' },
    { id: 'kids_52', name: 'Mächtige Magier', series: 'kids' },
    { id: 'kids_53', name: 'Geheimnis der Tiere', series: 'kids' },
    { id: 'kids_54', name: 'Zombie-Alarm', series: 'kids' },
    { id: 'kids_55', name: 'Der schwarze Joker', series: 'kids' },
    { id: 'kids_56', name: 'Das Rätsel der Könige', series: 'kids' },
    { id: 'kids_57', name: 'Der Weihnachtsdieb', series: 'kids' },
    { id: 'kids_58', name: 'Spur des Drachen', series: 'kids' },
    { id: 'kids_59', name: 'Fußballhelden', series: 'kids' },
    { id: 'kids_60', name: 'Gespensterjagd', series: 'kids' },
    { id: 'kids_61', name: 'Alarm im Dino-Park', series: 'kids' },
    { id: 'kids_62', name: 'Gefahr im Dschungel', series: 'kids' },
    { id: 'kids_63', name: 'Monster-Wolken', series: 'kids' },
    { id: 'kids_64', name: 'In der Schatzhöhle', series: 'kids' },
    { id: 'kids_65', name: 'Mission Goldhund', series: 'kids' },
    { id: 'kids_66', name: 'Geheimnis im Meer', series: 'kids' },
    { id: 'kids_67', name: 'Der goldene Drache', series: 'kids' },
    { id: 'kids_68', name: 'Chaos im Dunkeln', series: 'kids' },
    { id: 'kids_69', name: 'Die Rätselfalle', series: 'kids' },
    { id: 'kids_70', name: 'Aufbruch ins All', series: 'kids' },
    { id: 'kids_71', name: 'Tatort Trampolin', series: 'kids' },
    { id: 'kids_72', name: 'Die Laser-Falle', series: 'kids' },
    { id: 'kids_73', name: 'Surfstrand in Gefahr', series: 'kids' },
    { id: 'kids_74', name: 'Das Schienen-Monster', series: 'kids' },
    { id: 'kids_75', name: 'Der Fußball-Roboter', series: 'kids' },
    { id: 'kids_76', name: 'Blinde Passagiere', series: 'kids' },
    { id: 'kids_77', name: 'Die Musikdiebe', series: 'kids' },
    { id: 'kids_78', name: 'Schrottplatz in Gefahr', series: 'kids' },
    { id: 'kids_79', name: 'Achtung, Abenteuer!', series: 'kids' },
    { id: 'kids_80', name: 'Gefährlicher Nebel', series: 'kids' },
    { id: 'kids_81', name: 'Turbo-Rennen', series: 'kids' },
    { id: 'kids_82', name: 'Die Delfin-Piraten', series: 'kids' },
    { id: 'kids_83', name: 'Fußball-Diebe', series: 'kids' },
    { id: 'kids_84', name: 'Tatort Skater-Park', series: 'kids' },
    { id: 'kids_85', name: 'Falscher Alarm', series: 'kids' },
    { id: 'kids_86', name: 'Riesen in Rocky Beach', series: 'kids' },
    { id: 'kids_87', name: 'Das Geisterspiel', series: 'kids' },
    { id: 'kids_88', name: 'Schatz aus dem All', series: 'kids' },
    { id: 'kids_89', name: 'im Geistergarten', series: 'kids' },
    { id: 'kids_90', name: 'Flug ins Nichts', series: 'kids' },
    { id: 'kids_91', name: 'Gefahr im Spiegelkabinett', series: 'kids' },
    { id: 'kids_92', name: 'Spuk im Leuchtturm', series: 'kids' },
    { id: 'kids_93', name: 'Die Geistermühle', series: 'kids' },
    { id: 'kids_94', name: 'Falsche Vampire', series: 'kids' },
    { id: 'kids_95', name: 'Geheime Zeichen', series: 'kids' },
    { id: 'kids_96', name: 'Der Schrottkönig', series: 'kids' },
    { id: 'kids_97', name: 'Die Fragezeichen-Falle', series: 'kids' },
    { id: 'kids_98', name: 'Die Geisterpferde', series: 'kids' },
    { id: 'kids_99', name: 'Football-Falle', series: 'kids' },
    { id: 'kids_100', name: '100 Stunden', series: 'kids' },
    { id: 'kids_101', name: 'Geistermusik', series: 'kids' },
    { id: 'kids_102', name: 'Spur der Tresorknacker', series: 'kids' },
    { id: 'kids_103', name: 'SOS im Bike-Park', series: 'kids' },
    { id: 'kids_104', name: 'Teuflische Küche', series: 'kids' },
    { id: 'kids_105', name: 'Fiese Fälscherbande', series: 'kids' },
    { id: 'kids_106', name: 'Miese Doppelgänger', series: 'kids' },
    { id: 'kids_107', name: 'Fußball-Spione', series: 'kids' },
    { id: 'kids_108', name: 'Piraten in Rocky Beach', series: 'kids' },
    { id: 'kids_109', name: 'Fluch der Mumie', series: 'kids' },

    // Die drei ??? Kids - Ratekrimis
    { id: 'rate_01', name: 'Geheime Flaschenpost', series: 'kids_rate' },
    { id: 'rate_02', name: 'Fauler Zauber', series: 'kids_rate' },
    { id: 'rate_03', name: 'Schattendiebe', series: 'kids_rate' },
    { id: 'rate_04', name: 'Das Grusellabyrinth', series: 'kids_rate' },
    { id: 'rate_05', name: 'Geisterspuren', series: 'kids_rate' },
    { id: 'rate_06', name: 'Die Geistervilla', series: 'kids_rate' },
    { id: 'rate_07', name: 'Schräge Vögel', series: 'kids_rate' },
    { id: 'rate_08', name: 'Wilde Ganoven', series: 'kids_rate' },
    { id: 'rate_09', name: 'Verbrecher-Alarm', series: 'kids_rate' },

    // Die drei ??? Kids – und du
    { id: 'unddu_01', name: 'Seeschlangen-Spuk', series: 'kids_und_du' },
    { id: 'unddu_02', name: 'Im Rennfieber', series: 'kids_und_du' },
    { id: 'unddu_03', name: 'Im Auge des Orkans', series: 'kids_und_du' },
    { id: 'unddu_04', name: 'Vampire in Rocky Beach', series: 'kids_und_du' },
    { id: 'unddu_05', name: 'Der schwarze Drache', series: 'kids_und_du' },
    { id: 'unddu_06', name: 'Rocky Beach steht Kopf', series: 'kids_und_du' },
    { id: 'unddu_07', name: 'Rennbahn-Rivalen', series: 'kids_und_du' },
    { id: 'unddu_08', name: 'Angriff der Roboter', series: 'kids_und_du' },
    { id: 'unddu_09', name: 'Der Geisterfluss', series: 'kids_und_du' },
    { id: 'unddu_10', name: 'Die verhexte Achterbahn', series: 'kids_und_du' },
    { id: 'unddu_11', name: 'Das versunkene Gold', series: 'kids_und_du' },
    { id: 'unddu_12', name: 'Der Meisterdieb', series: 'kids_und_du' },
    { id: 'unddu_13', name: 'UFO-Alarm', series: 'kids_und_du' },
    { id: 'unddu_14', name: 'Der Wikingerschatz', series: 'kids_und_du' },
    { id: 'unddu_15', name: 'Die geheime Galaxie', series: 'kids_und_du' },
    { id: 'unddu_16', name: 'Spur ins Römergrab', series: 'kids_und_du' },
    { id: 'unddu_17', name: 'Zirkus der Rätsel', series: 'kids_und_du' },
    { id: 'unddu_18', name: 'Labyrinth der Piraten', series: 'kids_und_du' },
    { id: 'unddu_19', name: 'Das Grusellabyrinth', series: 'kids_und_du' },
    { id: 'unddu_20', name: 'Die geheimen Inseln', series: 'kids_und_du' },
    { id: 'unddu_21', name: 'Rocky Beach in Not', series: 'kids_und_du' },

    // Die drei ??? Kids – Sammelbände
    { id: 'kids_sammel_01', name: 'Alarm in Rocky Beach', series: 'kids_sammel' },
    { id: 'kids_sammel_02', name: 'Vorsicht, explosiv!', series: 'kids_sammel' },
    { id: 'kids_sammel_03', name: 'Piraten in Rocky Beach', series: 'kids_sammel' },
    { id: 'kids_sammel_04', name: 'Geisterstunde', series: 'kids_sammel' },
    { id: 'kids_sammel_05', name: 'Auf Rätseljagd', series: 'kids_sammel' },
    { id: 'kids_sammel_06', name: 'In Seenot', series: 'kids_sammel' },
    { id: 'kids_sammel_07', name: 'Faule Tricks', series: 'kids_sammel' },
    { id: 'kids_sammel_08', name: 'Fußballwunder', series: 'kids_sammel' },
    { id: 'kids_sammel_09', name: 'Geisternacht', series: 'kids_sammel' },
    { id: 'kids_sammel_10', name: 'Alarmstufe rot!', series: 'kids_sammel' },
    { id: 'kids_sammel_11', name: 'Tatort Wildnis', series: 'kids_sammel' },
    { id: 'kids_sammel_12', name: 'Fauler Zauber', series: 'kids_sammel' },
    { id: 'kids_sammel_13', name: 'Fußballweltmeister', series: 'kids_sammel' },
    { id: 'kids_sammel_14', name: 'Superhelden', series: 'kids_sammel' },

    // Die drei ??? Kids – Sonderbände
    { id: 'kids_sonder_01', name: 'Meine Freunde', series: 'kids_sonder' },
    { id: 'kids_sonder_02', name: 'Der Adventskalender 2010', series: 'kids_sonder' },
    { id: 'kids_sonder_03', name: 'Detektivhandbuch', series: 'kids_sonder' },
    { id: 'kids_sonder_04', name: 'Das geheime Buch', series: 'kids_sonder' },
    { id: 'kids_sonder_05', name: 'Der Adventskalender 2011', series: 'kids_sonder' },
    { id: 'kids_sonder_06', name: 'Mein Schulanfang', series: 'kids_sonder' },
    { id: 'kids_sonder_07', name: 'Gefährliche Schatzsuche', series: 'kids_sonder' },
    { id: 'kids_sonder_08', name: 'Der Kirschkuchendieb', series: 'kids_sonder' },
    { id: 'kids_sonder_09', name: 'Der Adventskalender 2012', series: 'kids_sonder' },
    { id: 'kids_sonder_10', name: 'Mission Pinguin', series: 'kids_sonder' },
    { id: 'kids_sonder_11', name: 'Das gefährlichste Buch der Welt', series: 'kids_sonder' },
    { id: 'kids_sonder_12', name: 'Die versunkene Stadt', series: 'kids_sonder' },
    { id: 'kids_sonder_13', name: 'Der Adventskalender 2013', series: 'kids_sonder' },
    { id: 'kids_sonder_14', name: 'Spuk in der Schule', series: 'kids_sonder' },
    { id: 'kids_sonder_15', name: 'Strandpiraten – Comic', series: 'kids_sonder' },
    { id: 'kids_sonder_16', name: 'Der Adventskalender 2014', series: 'kids_sonder' },
    { id: 'kids_sonder_17', name: 'Diamanten-Diebe', series: 'kids_sonder' },
    { id: 'kids_sonder_18', name: 'Happy Birthday – Ein Fall für deinen Geburtstag', series: 'kids_sonder' },
    { id: 'kids_sonder_19', name: 'Das gruseligste Buch aller Zeiten', series: 'kids_sonder' },
    { id: 'kids_sonder_20', name: 'Der Adventskalender 2015', series: 'kids_sonder' },
    { id: 'kids_sonder_21', name: 'Ruf der Waldgeister', series: 'kids_sonder' },
    { id: 'kids_sonder_22', name: 'Bundesliga-Alarm', series: 'kids_sonder' },
    { id: 'kids_sonder_23', name: 'Vorsicht, Verbrecher! – Comic', series: 'kids_sonder' },
    { id: 'kids_sonder_24', name: 'Der Adventskalender 2016', series: 'kids_sonder' },
    { id: 'kids_sonder_25', name: 'Bücherhelden – Die Räuberjagd', series: 'kids_sonder' },
    { id: 'kids_sonder_26', name: 'Bücherhelden – Vorsicht, Zaubertinte!', series: 'kids_sonder' },
    { id: 'kids_sonder_27', name: 'Bücherhelden – Die Piratenbande', series: 'kids_sonder' },
    { id: 'kids_sonder_28', name: 'Das außerirdische Buch', series: 'kids_sonder' },
    { id: 'kids_sonder_29', name: 'Der Adventskalender 2017', series: 'kids_sonder' },
    { id: 'kids_sonder_30', name: 'Die Wikinger kommen! – Comic', series: 'kids_sonder' },
    { id: 'kids_sonder_31', name: 'Bücherhelden – Achtung, Dinos!', series: 'kids_sonder' },
    { id: 'kids_sonder_32', name: 'Witze zum Schrottlachen', series: 'kids_sonder' },
    { id: 'kids_sonder_33', name: 'Der Adventskalender 2018', series: 'kids_sonder' },
    { id: 'kids_sonder_34', name: 'Weihnachtsrätselbuch', series: 'kids_sonder' },
    { id: 'kids_sonder_35', name: 'Bücherhelden – Alarm, die Ritter kommen!', series: 'kids_sonder' },
    { id: 'kids_sonder_36', name: 'SOS Schnitzeljagd', series: 'kids_sonder' },
    { id: 'kids_sonder_37', name: 'Diamantenraub – Comic', series: 'kids_sonder' },
    { id: 'kids_sonder_38', name: 'Bücherhelden – Der Monster-Schreck', series: 'kids_sonder' },
    { id: 'kids_sonder_39', name: 'Das ekligste Buch aller Zeiten', series: 'kids_sonder' },
    { id: 'kids_sonder_40', name: 'Bücherhelden – Hilfe, Geisterzug!', series: 'kids_sonder' },
    { id: 'kids_sonder_41', name: 'Der Adventskalender 2019', series: 'kids_sonder' },
    { id: 'kids_sonder_42', name: 'Chaos in Rocky Beach! – Comic', series: 'kids_sonder' },
    { id: 'kids_sonder_43', name: 'Bücherhelden – Ungeheuer in Sicht!', series: 'kids_sonder' },
    { id: 'kids_sonder_44', name: 'Mission Graffiti-Code', series: 'kids_sonder' },
    { id: 'kids_sonder_45', name: 'Team Bundesliga', series: 'kids_sonder' },
    { id: 'kids_sonder_46', name: 'Bücherhelden – Der unsichtbare Dieb', series: 'kids_sonder' },
    { id: 'kids_sonder_47', name: 'Tanz der Piraten', series: 'kids_sonder' },
    { id: 'kids_sonder_48', name: 'Der Adventskalender 2020', series: 'kids_sonder' },
    { id: 'kids_sonder_49', name: 'Bücherhelden – Drachen-Alarm!', series: 'kids_sonder' },
    { id: 'kids_sonder_50', name: 'Fußball, Ferien, Freunde! – Comic', series: 'kids_sonder' },
    { id: 'kids_sonder_51', name: 'Das verrückteste Buch aller Zeiten', series: 'kids_sonder' },
    { id: 'kids_sonder_52', name: 'Mission Kaugummi-Code', series: 'kids_sonder' },
    { id: 'kids_sonder_53', name: 'Bücherhelden – Geheime Flaschenpost', series: 'kids_sonder' },
    { id: 'kids_sonder_54', name: 'Bücherhelden – Hunde in Gefahr', series: 'kids_sonder' },
    { id: 'kids_sonder_55', name: 'Der Adventskalender 2021', series: 'kids_sonder' },
    { id: 'kids_sonder_56', name: 'Dein Fall – Das Gruselschloss', series: 'kids_sonder' },
    { id: 'kids_sonder_57', name: 'Bücherhelden – Der Wüstengeist', series: 'kids_sonder' },
    { id: 'kids_sonder_58', name: 'Diebstahl im Eiscafé – Das große Rätselbuch', series: 'kids_sonder' },
    { id: 'kids_sonder_59', name: 'Bücherhelden – Tatort Dschungel', series: 'kids_sonder' },
    { id: 'kids_sonder_60', name: 'Bücherhelden – Verrücktes Fußballspiel', series: 'kids_sonder' },
    { id: 'kids_sonder_61', name: 'Rettet Rocky Beach', series: 'kids_sonder' },
    { id: 'kids_sonder_62', name: 'Mission Fußball-Code', series: 'kids_sonder' },
    { id: 'kids_sonder_63', name: 'Der Adventskalender 2022', series: 'kids_sonder' },
    { id: 'kids_sonder_64', name: 'Bücherhelden – Rätselhafte Schatzsuche', series: 'kids_sonder' },
    { id: 'kids_sonder_65', name: 'Dein Fall – Das Wüstenschiff', series: 'kids_sonder' },
    { id: 'kids_sonder_66', name: 'Gruselnächte in Rocky Beach – Comic', series: 'kids_sonder' },
    { id: 'kids_sonder_67', name: 'Diebstahl im All', series: 'kids_sonder' },
    { id: 'kids_sonder_68', name: 'Ferienrätselbuch', series: 'kids_sonder' },
    { id: 'kids_sonder_69', name: 'Das teuerste Buch aller Zeiten', series: 'kids_sonder' },
    { id: 'kids_sonder_70', name: 'Die Rekorde-Jagd', series: 'kids_sonder' },
    { id: 'kids_sonder_71', name: 'Bücherhelden - Feuerwehr-Alarm', series: 'kids_sonder' },
    { id: 'kids_sonder_72', name: 'Bücherhelden - Die Weihnachtsräuber', series: 'kids_sonder' },
    { id: 'kids_sonder_73', name: 'Adventskalender 2023 - 24 Tage Elfen-Alarm', series: 'kids_sonder' },
    { id: 'kids_sonder_74', name: 'Dein Fall - Die Golddiebe', series: 'kids_sonder' },
    { id: 'kids_sonder_75', name: 'Das Kirsch-Komplott - Comic', series: 'kids_sonder' },
    { id: 'kids_sonder_76', name: 'Bücherhelden - Geister in der Schule', series: 'kids_sonder' },
    { id: 'kids_sonder_77', name: 'Der Schatz der Götter', series: 'kids_sonder' },
    { id: 'kids_sonder_78', name: 'Der schwarze Diamant', series: 'kids_sonder' },
    { id: 'kids_sonder_79', name: 'Adventskalender 2024 - 24 Tage Weihnachtsparade', series: 'kids_sonder' },
    { id: 'kids_sonder_80', name: 'Geheimnis um CubeMax', series: 'kids_sonder' },
    { id: 'kids_sonder_81', name: 'Bücherhelden - Vorsicht, Zombies!', series: 'kids_sonder' },
    { id: 'kids_sonder_82', name: 'Das schleimigste Buch aller Zeiten', series: 'kids_sonder' },
    { id: 'kids_sonder_83', name: 'Dein Fall - Das Spukhotel', series: 'kids_sonder' },
    { id: 'kids_sonder_84', name: 'Mission Piraten-Code', series: 'kids_sonder' },
    { id: 'kids_sonder_85', name: 'Bücherhelden - Vorsicht Ninjas!', series: 'kids_sonder' },
    { id: 'kids_sonder_86', name: 'Der Adventskalender 2025', series: 'kids_sonder' },
    { id: 'kids_sonder_87', name: 'Gefangen in CubeMax', series: 'kids_sonder' },
    { id: 'kids_sonder_88', name: 'Das Dino-Geheimnis', series: 'kids_sonder' },
    { id: 'kids_sonder_89', name: 'Abenteuer in Rocky Beach - Comic', series: 'kids_sonder' },
    { id: 'kids_sonder_90', name: 'Bücherhelden - Vulkan in Rocky Beach', series: 'kids_sonder' },
    { id: 'kids_sonder_91', name: 'Bücherhelden - Spuk in der Wüste', series: 'kids_sonder' },
    { id: 'kids_sonder_92', name: 'CubeMax in Gefahr', series: 'kids_sonder' },

    // Die drei ??? Kids – Minibände
    { id: 'kids_mini_01', name: 'Piraten an Bord', series: 'kids_mini' },
    { id: 'kids_mini_02', name: 'Die Müllmonster', series: 'kids_mini' },
    { id: 'kids_mini_03', name: 'Vorsicht, Falschgeld', series: 'kids_mini' },
    { id: 'kids_mini_04', name: 'Verhexter Regentanz', series: 'kids_mini' },
    { id: 'kids_mini_05', name: 'Rätseljagd', series: 'kids_mini' },
    { id: 'kids_mini_06', name: 'Delfine in Not', series: 'kids_mini' },
    { id: 'kids_mini_07', name: 'Das Rätsel der Marabus', series: 'kids_mini' },
    { id: 'kids_mini_08', name: 'Astronaut in Gefahr', series: 'kids_mini' },
    { id: 'kids_mini_09', name: 'Monster-Trucks', series: 'kids_mini' },
    { id: 'kids_mini_10', name: 'Insekten-Alarm', series: 'kids_mini' },
    { id: 'kids_mini_11', name: 'Achtung, Strandräuber!', series: 'kids_mini' },
    { id: 'kids_mini_12', name: 'Eiskaltes Spiel', series: 'kids_mini' },
    { id: 'kids_mini_13', name: 'Der Spinnenmensch', series: 'kids_mini' },
    { id: 'kids_mini_14', name: 'Die Matschbombe', series: 'kids_mini' },
    { id: 'kids_mini_15', name: 'Achtung, Katzendiebe!', series: 'kids_mini' },
    { id: 'kids_mini_16', name: 'Jagd im Dunkeln', series: 'kids_mini' },
    { id: 'kids_mini_17', name: 'Kampf der Roboter', series: 'kids_mini' },
    { id: 'kids_mini_18', name: 'Baskettball-Fieber', series: 'kids_mini' },
    { id: 'kids_mini_19', name: 'Gefährliche Wellen', series: 'kids_mini' },
    { id: 'kids_mini_20', name: 'Gauner in Rocky Beach', series: 'kids_mini' },
    { id: 'kids_mini_21', name: 'Tiere in Not', series: 'kids_mini' }
];

console.log('Die drei ??? - Komplette Buchliste geladen');
console.log(`Serien: ${series.length}`);
console.log(`Bücher gesamt: ${books.length}`);
console.log(`- Klassiker: ${books.filter(b => b.series === 'klassiker').length}`);
console.log(`- Neuzeit: ${books.filter(b => b.series === 'neuzeit').length}`);
console.log(`- Kids Hauptreihe: ${books.filter(b => b.series === 'hauptreihe').length}`);